<?xml version="1.0" encoding="utf-8"?><Database Name="AdventureWorks" Class="LDSongDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-50CH9TG\SQLEXPRESS2;Initial Catalog=AdventureWorks;Integrated Security=True" SettingsObjectName="LDSong.Properties.Settings" SettingsPropertyName="AdventureWorksConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.D_CAP_DAP" Member="D_CAP_DAPs">
    <Type Name="D_CAP_DAP">
      <Column Name="MA_CAPDA" Type="System.String" DbType="NVarChar(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MA_PMIS" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="TEN_CAPDA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="STT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="D_CAP_DAP_D_PTDIEN" Member="D_PTDIENs" ThisKey="MA_CAPDA" OtherKey="MA_CAPDA" Type="D_PTDIEN" />
    </Type>
  </Table>
  <Table Name="dbo.D_LOAI_TBI" Member="D_LOAI_TBIs">
    <Type Name="D_LOAI_TBI">
      <Column Name="MA_LOAI" Type="System.String" DbType="NVarChar(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TEN_LOAI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="D_LOAI_TBI_D_PTDIEN" Member="D_PTDIENs" ThisKey="MA_LOAI" OtherKey="LOAI_PTDIEN" Type="D_PTDIEN" />
    </Type>
  </Table>
  <Table Name="dbo.D_QHE_PTDIEN" Member="D_QHE_PTDIENs">
    <Type Name="D_QHE_PTDIEN">
      <Column Name="ID_QHE" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_PTDIEN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_PTCHA" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NGAY_HLUC" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NGAY_TAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGUOI_TAO" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="NGAY_SUA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGUOI_SUA" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Association Name="D_PTDIEN_D_QHE_PTDIEN" Member="D_PTDIEN" ThisKey="ID_PTDIEN" OtherKey="ID_PTDIEN" Type="D_PTDIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.S_MENU" Member="S_MENUs">
    <Type Name="S_MENU">
      <Column Name="MenuId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MenuLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MenuName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MenuButton" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MenuOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.S_USER" Member="S_USERs">
    <Type Name="S_USER">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaDVQL" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaPBan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="UserPassword" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserGroup" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserFullname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserPoss" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastLogin" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="IsManager" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="S_GROUP_S_USER" Member="S_GROUP" ThisKey="UserGroup" OtherKey="GroupId" Type="S_GROUP" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.D_LOAI_YCAU" Member="D_LOAI_YCAUs">
    <Type Name="D_LOAI_YCAU">
      <Column Name="MA_LOAI" Type="System.String" DbType="NVarChar(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TEN_LOAI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.S_GROUP" Member="S_GROUPs">
    <Type Name="S_GROUP">
      <Column Name="GroupId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GroupName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GroupDesc" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Permission" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="S_GROUP_S_USER" Member="S_USERs" ThisKey="GroupId" OtherKey="UserGroup" Type="S_USER" />
    </Type>
  </Table>
  <Table Name="dbo.K_DIEM_DO" Member="K_DIEM_DOs">
    <Type Name="K_DIEM_DO">
      <Column Name="MA_DVIQLY" Type="System.String" DbType="NVarChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MA_KHANG" Type="System.String" DbType="NVarChar(13)" CanBeNull="true" />
      <Column Name="MA_DDO" Type="System.String" DbType="NVarChar(16) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SO_CTO" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="MA_SOGCS" Type="System.String" DbType="NVarChar(9)" CanBeNull="true" />
      <Column Name="STT" Type="System.String" DbType="NVarChar(6)" CanBeNull="true" />
      <Column Name="MA_TRAM" Type="System.String" DbType="NVarChar(9)" CanBeNull="true" />
      <Column Name="MA_LO" Type="System.String" DbType="NVarChar(9)" CanBeNull="true" />
      <Column Name="SO_COT" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="SO_HOM" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="NGAY_DBO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.K_KHACH_HANG" Member="K_KHACH_HANGs">
    <Type Name="K_KHACH_HANG">
      <Column Name="MA_DVIQLY" Type="System.String" DbType="NVarChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MA_KHANG" Type="System.String" DbType="NVarChar(13) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TEN_KHANG" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DIA_CHI" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DIEN_THOAI" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NGAY_DBO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="K_KHACH_HANG_K_YEU_CAU" Member="K_YEU_CAUs" ThisKey="MA_KHANG" OtherKey="MA_KHANG" Type="K_YEU_CAU" />
    </Type>
  </Table>
  <Table Name="dbo.M_VITRI_V2" Member="M_VITRI_V2s">
    <Type Name="M_VITRI_V2">
      <Column Name="ID_PTDIEN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MA_DVQLY" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="MA_PTDIEN" Type="System.String" DbType="NVarChar(9)" CanBeNull="true" />
      <Column Name="MA_PMIS" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TOA_DO" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="MA_CAPDA" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="TEN_PTDIEN" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="LOAI_PTDIEN" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="MA_PMISCHA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MA_SCADA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MA_CMIS" Type="System.String" DbType="NVarChar(9)" CanBeNull="true" />
      <Column Name="TRANG_THAI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="THOI_DIEM" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.HISTORY_DELETE_DPTIDEN" Member="HISTORY_DELETE_DPTIDENs">
    <Type Name="HISTORY_DELETE_DPTIDEN">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MA_DVQLY" Type="System.String" DbType="NVarChar(6)" CanBeNull="true" />
      <Column Name="ID_PTDIEN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TEN_PTDIEN" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="MA_CAPDA" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="TEN_CAPDA" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="LOAI_PTDIEN" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="NGAY_TAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGUOI_TAO" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="NGAY_SUA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGUOI_SUA" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="MA_CMIS" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MA_PMIS" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MA_SCADA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MA_PMISCHA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NGUOI_XOA" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="NGAY_XOA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.HISTORY_LOGIN" Member="HISTORY_LOGINs">
    <Type Name="HISTORY_LOGIN">
      <Column Name="USERNAME" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="THOIGIAN_DANGNHAP" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="THOIGIAN_DANGXUAT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IP_CONNETION" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ID_HS" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.M_VITRI_V" Member="M_VITRI_Vs">
    <Type Name="M_VITRI_V">
      <Column Name="ID_PTDIEN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MA_DVQLY" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="TEN_PTDIEN" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="LOAI_PTDIEN" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="MA_CAPDA" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="MA_CMIS" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LEFT_TRANGTHAI" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RIGHT_TRANGTHAI" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NGAY_CAP_NHAT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.S_BAOCAO" Member="S_BAOCAOs">
    <Type Name="S_BAOCAO">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MABC" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="TENBAOCAO" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TIEUDEBAOCAO" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="CHUCDANH" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NGUOIKY" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.HISTORY_TTHAI_PTDIEN" Member="HISTORY_TTHAI_PTDIENs">
    <Type Name="HISTORY_TTHAI_PTDIEN">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MA_DVQLY" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="ID_PTDIEN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TRANG_THAI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="THOI_DIEM" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.M_TTHAI_PTDIEN_CMIS" Member="M_TTHAI_PTDIEN_CMIs">
    <Type Name="M_TTHAI_PTDIEN_CMI">
      <Column Name="ID_TTHAI" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_PTDIEN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TagName" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Value" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TimeStamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.D_PTDIEN" Member="D_PTDIENs">
    <Type Name="D_PTDIEN">
      <Column Name="MA_DVQLY" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="ID_PTDIEN" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TEN_PTDIEN" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="MA_CAPDA" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="TEN_CAPDA" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="LOAI_PTDIEN" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="NGAY_TAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGUOI_TAO" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="NGAY_SUA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGUOI_SUA" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="MA_CMIS" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CONGSUAT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MA_PMIS" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MA_SCADA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MA_PMISCHA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="D_PTDIEN_D_QHE_PTDIEN" Member="D_QHE_PTDIENs" ThisKey="ID_PTDIEN" OtherKey="ID_PTDIEN" Type="D_QHE_PTDIEN" />
      <Association Name="D_PTDIEN_M_TTHAI_CD_KDCB" Member="M_TTHAI_CD_KDCBs" ThisKey="ID_PTDIEN" OtherKey="ID_PTDIEN" Type="M_TTHAI_CD_KDCB" />
      <Association Name="D_PTDIEN_M_TTHAI_PTDIEN" Member="M_TTHAI_PTDIENs" ThisKey="ID_PTDIEN" OtherKey="ID_PTDIEN" Type="M_TTHAI_PTDIEN" />
      <Association Name="D_PTDIEN_D_QHE_PTDIEN_VITRI" Member="D_QHE_PTDIEN_VITRIs" ThisKey="ID_PTDIEN" OtherKey="ID_PTDienCon" Type="D_QHE_PTDIEN_VITRI" />
      <Association Name="D_PTDIEN_M_TTHAI_PTDIEN_VM" Member="M_TTHAI_PTDIEN_VMs" ThisKey="ID_PTDIEN" OtherKey="ID_PTDIEN" Type="M_TTHAI_PTDIEN_VM" />
      <Association Name="D_PTDIEN_M_TTHAI_PTDIEN_LR_VM" Member="M_TTHAI_PTDIEN_LR_VMs" ThisKey="ID_PTDIEN" OtherKey="ID_PTDIEN" Type="M_TTHAI_PTDIEN_LR_VM" />
      <Association Name="D_PTDIEN_M_TTHAI_PTDIEN_LR" Member="M_TTHAI_PTDIEN_LRs" ThisKey="ID_PTDIEN" OtherKey="ID_PTDIEN" Type="M_TTHAI_PTDIEN_LR" />
      <Association Name="D_PTDIEN_D_CAY_TON_THAT" Member="D_CAY_TON_THATs" ThisKey="ID_PTDIEN" OtherKey="ID_PTDIEN" Type="D_CAY_TON_THAT" />
      <Association Name="D_PTDIEN_D_ChiTiet_TBA" Member="D_ChiTiet_TBAs" ThisKey="ID_PTDIEN" OtherKey="ID_PTDIEN" Type="D_ChiTiet_TBA" />
      <Association Name="D_PTDIEN_D_Image" Member="D_Images" ThisKey="ID_PTDIEN" OtherKey="ID_PTDIEN" Type="D_Image" />
      <Association Name="D_LOAI_TBI_D_PTDIEN" Member="D_LOAI_TBI" ThisKey="LOAI_PTDIEN" OtherKey="MA_LOAI" Type="D_LOAI_TBI" IsForeignKey="true" />
      <Association Name="D_CAP_DAP_D_PTDIEN" Member="D_CAP_DAP" ThisKey="MA_CAPDA" OtherKey="MA_CAPDA" Type="D_CAP_DAP" IsForeignKey="true" />
      <Association Name="D_DVI_QLY_D_PTDIEN" Member="D_DVI_QLY" ThisKey="MA_DVQLY" OtherKey="MA_DVIQLY" Type="D_DVI_QLY" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.M_TTHAI_CD_KDCB" Member="M_TTHAI_CD_KDCBs">
    <Type Name="M_TTHAI_CD_KDCB">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_PTDIEN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="D_PTDIEN_M_TTHAI_CD_KDCB" Member="D_PTDIEN" ThisKey="ID_PTDIEN" OtherKey="ID_PTDIEN" Type="D_PTDIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.M_VITRI_V0" Member="M_VITRI_V0s">
    <Type Name="M_VITRI_V0">
      <Column Name="ID_PTDIEN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MA_DVQLY" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="TEN_PTDIEN" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="LOAI_PTDIEN" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="MA_CAPDA" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="MA_CMIS" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TRANG_THAI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="THOI_DIEM" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.M_TTHAI_PTDIEN" Member="M_TTHAI_PTDIENs">
    <Type Name="M_TTHAI_PTDIEN">
      <Column Name="ID_TTHAI" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MA_DVQLY" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ID_PTDIEN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TRANG_THAI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="THOI_DIEM" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="THOIGIANKETTHUC" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Association Name="D_PTDIEN_M_TTHAI_PTDIEN" Member="D_PTDIEN" ThisKey="ID_PTDIEN" OtherKey="ID_PTDIEN" Type="D_PTDIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.D_QHE_PTDIEN_VITRI" Member="D_QHE_PTDIEN_VITRIs">
    <Type Name="D_QHE_PTDIEN_VITRI">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_PTDienCha" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_PTDienCon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TENPTDienCon" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="VITRI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NGAYCAPNHAT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="USERNAME" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Association Name="D_PTDIEN_D_QHE_PTDIEN_VITRI" Member="D_PTDIEN" ThisKey="ID_PTDienCon" OtherKey="ID_PTDIEN" Type="D_PTDIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.M_VITRI_V1_VM" Member="M_VITRI_V1_VMs">
    <Type Name="M_VITRI_V1_VM">
      <Column Name="ID_PTDIEN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MA_DVQLY" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="MA_PTDIEN" Type="System.String" DbType="NVarChar(9)" CanBeNull="true" />
      <Column Name="MA_PMIS" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TOA_DO" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="MA_CAPDA" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="TEN_PTDIEN" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="LOAI_PTDIEN" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="MA_PMISCHA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MA_SCADA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MA_CMIS" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LEFT_TRANGTHAI" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RIGHT_TRANGTHAI" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CHIEUDONGDIEN" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NGAY_CAP_NHAT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.M_VITRI_V2_VM" Member="M_VITRI_V2_VMs">
    <Type Name="M_VITRI_V2_VM">
      <Column Name="ID_PTDIEN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MA_DVQLY" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="MA_PTDIEN" Type="System.String" DbType="NVarChar(9)" CanBeNull="true" />
      <Column Name="MA_PMIS" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TOA_DO" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="MA_CAPDA" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="TEN_PTDIEN" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="LOAI_PTDIEN" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="MA_PMISCHA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MA_SCADA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MA_CMIS" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TRANG_THAI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="THOI_DIEM" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.M_TTHAI_PTDIEN_VM" Member="M_TTHAI_PTDIEN_VMs">
    <Type Name="M_TTHAI_PTDIEN_VM">
      <Column Name="ID_TTHAI" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MA_DVQLY" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ID_PTDIEN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TRANG_THAI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="THOI_DIEM" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="THOIGIANKETTHUC" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Association Name="D_PTDIEN_M_TTHAI_PTDIEN_VM" Member="D_PTDIEN" ThisKey="ID_PTDIEN" OtherKey="ID_PTDIEN" Type="D_PTDIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.M_TTHAI_PTDIEN_LR_VM" Member="M_TTHAI_PTDIEN_LR_VMs">
    <Type Name="M_TTHAI_PTDIEN_LR_VM">
      <Column Name="ID_PTDIEN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LEFT_TRANGTHAI" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RIGHT_TRANGTHAI" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CHIEUDONGDIEN" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NGAY_CAP_NHAT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="THOIGIANKETTHUC" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGUYENNHAN" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="D_PTDIEN_M_TTHAI_PTDIEN_LR_VM" Member="D_PTDIEN" ThisKey="ID_PTDIEN" OtherKey="ID_PTDIEN" Type="D_PTDIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.M_VITRI_SD1S_DZ_V" Member="M_VITRI_SD1S_DZ_Vs">
    <Type Name="M_VITRI_SD1S_DZ_V">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENDZ" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="MA_DVQL" Type="System.String" DbType="NVarChar(6)" CanBeNull="true" />
      <Column Name="MA_CAPDA" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="VITRI" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.M_VITRI_SD1S_V2" Member="M_VITRI_SD1S_V2s">
    <Type Name="M_VITRI_SD1S_V2">
      <Column Name="ID_PTDIEN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KIEU" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="MA_DVQLY" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="VITRI" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="MA_CAPDA" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="TEN_PTDIEN" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="LOAI_PTDIEN" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="TRANG_THAI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="THOI_DIEM" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.M_NOTE_V" Member="M_NOTE_Vs">
    <Type Name="M_NOTE_V">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NDGHICHU" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="VITRI" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SIZEFONT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MA_DVQL" Type="System.String" DbType="NVarChar(6)" CanBeNull="true" />
      <Column Name="MA_CAPDA" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.M_VITRI_V_VM" Member="M_VITRI_V_VMs">
    <Type Name="M_VITRI_V_VM">
      <Column Name="ID_PTDIEN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MA_DVQLY" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="TEN_PTDIEN" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="LOAI_PTDIEN" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="MA_CAPDA" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="MA_CMIS" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LEFT_TRANGTHAI" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RIGHT_TRANGTHAI" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NGAY_CAP_NHAT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.M_VITRI_V0_VM" Member="M_VITRI_V0_VMs">
    <Type Name="M_VITRI_V0_VM">
      <Column Name="ID_PTDIEN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MA_DVQLY" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="TEN_PTDIEN" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="LOAI_PTDIEN" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="MA_CAPDA" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="MA_CMIS" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TRANG_THAI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="THOI_DIEM" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.K_YEU_CAU" Member="K_YEU_CAUs">
    <Type Name="K_YEU_CAU">
      <Column Name="ID_YCAU" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MA_LOAI" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="MA_DVIQLY" Type="System.String" DbType="NVarChar(6)" CanBeNull="true" />
      <Column Name="MA_KHANG" Type="System.String" DbType="NVarChar(13)" CanBeNull="true" />
      <Column Name="NOI_DUNG" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="NGAY_TAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TT_LienHe" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TINH_TRANG" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="NGUOI_XU_LY" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="NGUOI_CAP_NHAT" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Association Name="K_KHACH_HANG_K_YEU_CAU" Member="K_KHACH_HANG" ThisKey="MA_KHANG" OtherKey="MA_KHANG" Type="K_KHACH_HANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.M_TTHAI_PTDIEN_LR" Member="M_TTHAI_PTDIEN_LRs">
    <Type Name="M_TTHAI_PTDIEN_LR">
      <Column Name="ID_PTDIEN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LEFT_TRANGTHAI" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RIGHT_TRANGTHAI" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CHIEUDONGDIEN" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="NGAY_CAP_NHAT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="THOIGIANKETTHUC" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGUYENNHAN" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="D_PTDIEN_M_TTHAI_PTDIEN_LR" Member="D_PTDIEN" ThisKey="ID_PTDIEN" OtherKey="ID_PTDIEN" Type="D_PTDIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HISTORY_TTHAI_PTDIEN_LR" Member="HISTORY_TTHAI_PTDIEN_LRs">
    <Type Name="HISTORY_TTHAI_PTDIEN_LR">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_PTDIEN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LEFT_TRANGTHAI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RIGHT_TRANGTHAI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CHIEUDONGDIEN" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="NGAY_CAP_NHAT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="THOIGIANKETTHUC" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGUYENNHAN" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.M_VITRI_V3" Member="M_VITRI_V3s">
    <Type Name="M_VITRI_V3">
      <Column Name="ID_PTDIEN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MA_DVQLY" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="MA_PTDIEN" Type="System.String" DbType="NVarChar(9)" CanBeNull="true" />
      <Column Name="MA_PMIS" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TOA_DO" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="MA_CAPDA" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="TEN_PTDIEN" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="LOAI_PTDIEN" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="MA_PMISCHA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MA_SCADA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MA_CMIS" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LEFT_TRANGTHAI" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RIGHT_TRANGTHAI" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NGUYENNHAN" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="NGAY_CAP_NHAT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CHIEUDONGDIEN" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.M_VITRI_V1" Member="M_VITRI_V1s">
    <Type Name="M_VITRI_V1">
      <Column Name="ID_PTDIEN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MA_DVQLY" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="MA_PTDIEN" Type="System.String" DbType="NVarChar(9)" CanBeNull="true" />
      <Column Name="MA_PMIS" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TOA_DO" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="MA_CAPDA" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="TEN_PTDIEN" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="LOAI_PTDIEN" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="MA_PMISCHA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MA_SCADA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MA_CMIS" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LEFT_TRANGTHAI" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RIGHT_TRANGTHAI" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NGUYENNHAN" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="NGAY_CAP_NHAT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.K_THONGSO_V" Member="K_THONGSO_Vs">
    <Type Name="K_THONGSO_V">
      <Column Name="MA_TRAM" Type="System.String" DbType="NVarChar(9)" CanBeNull="true" />
      <Column Name="MA_CTO" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="SO_CTO" Type="System.String" DbType="NVarChar(26)" CanBeNull="true" />
      <Column Name="IA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IB" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IC" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="UA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="UB" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="UC" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="COSA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="COSB" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="COSC" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="COS" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TB" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TC" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PB" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PC" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="P" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="QA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="QB" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="QC" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Q" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="QG" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="QN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PG1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PG2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PG3" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PG" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PN1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PN2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PN3" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PMAX" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TIME_PMAX" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAY_NHAN" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.K_THONGSO_CB_V" Member="K_THONGSO_CB_Vs">
    <Type Name="K_THONGSO_CB_V">
      <Column Name="ID_THONGSO" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TagName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="IA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IB" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IC" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="UA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="UB" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="UC" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="COSA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="COSB" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="COSC" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="COS" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TB" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TC" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PB" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PC" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="P" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="QA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="QB" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="QC" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Q" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="QG" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="QN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PG1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PG2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PG3" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PG" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PN1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PN2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PN3" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PMAX" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TIME_PMAX" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAY_NHAN" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.D_DVI_QLY" Member="D_DVI_QLies">
    <Type Name="D_DVI_QLY">
      <Column Name="MA_DVIQLY" Type="System.String" DbType="NVarChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TEN_DVIQLY" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="DIA_CHI" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="DIEN_THOAI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TOA_DO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="D_DVI_QLY_D_PTDIEN" Member="D_PTDIENs" ThisKey="MA_DVIQLY" OtherKey="MA_DVQLY" Type="D_PTDIEN" />
    </Type>
  </Table>
  <Table Name="dbo.D_CAY_TON_THAT" Member="D_CAY_TON_THATs">
    <Type Name="D_CAY_TON_THAT">
      <Column Name="ID_QHE" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_PTDIEN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_PTCHA" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NGAY_LAY_CAY" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="D_PTDIEN_D_CAY_TON_THAT" Member="D_PTDIEN" ThisKey="ID_PTDIEN" OtherKey="ID_PTDIEN" Type="D_PTDIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Bypass" Member="Bypasses">
    <Type Name="Bypass">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Check_Dong" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.M_VITRI_SD1S_V" Member="M_VITRI_SD1S_Vs">
    <Type Name="M_VITRI_SD1S_V">
      <Column Name="ID_PTDIEN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MA_DVQLY" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="VITRI" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="MA_CAPDA" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="LOAI_PTDIEN" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.M_VITRI_V5_All" Member="M_VITRI_V5_Alls">
    <Type Name="M_VITRI_V5_All">
      <Column Name="ID_PTDIEN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MA_DVQLY" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="MA_PTDIEN" Type="System.String" DbType="NVarChar(9)" CanBeNull="true" />
      <Column Name="MA_PMIS" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TOA_DO" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="MA_CAPDA" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="TEN_PTDIEN" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="LOAI_PTDIEN" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="MA_PMISCHA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MA_SCADA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MA_CMIS" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LEFT_TRANGTHAI" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RIGHT_TRANGTHAI" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NGUYENNHAN" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="NGAY_CAP_NHAT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="THOIGIANKETTHUC" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.M_VITRI_V5_ALL_TT" Member="M_VITRI_V5_ALL_TTs">
    <Type Name="M_VITRI_V5_ALL_TT">
      <Column Name="ID_PTDIEN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MA_DVQLY" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="MA_PTDIEN" Type="System.String" DbType="NVarChar(9)" CanBeNull="true" />
      <Column Name="MA_PMIS" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TOA_DO" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="MA_CAPDA" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="TEN_PTDIEN" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="LOAI_PTDIEN" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="MA_PMISCHA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MA_SCADA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MA_CMIS" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TRANG_THAI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="THOI_DIEM" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Version" Member="Versions">
    <Type Name="Version">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Version" Member="Version1" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.D_ChiTiet_TBA" Member="D_ChiTiet_TBAs">
    <Type Name="D_ChiTiet_TBA">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_PTDIEN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Sdm" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Udm1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Udm2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Idm1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Idm2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="UN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="I0" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="P0" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="fHz" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Trong_Luong_TBA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Trong_Luong_Dau" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Association Name="D_PTDIEN_D_ChiTiet_TBA" Member="D_PTDIEN" ThisKey="ID_PTDIEN" OtherKey="ID_PTDIEN" Type="D_PTDIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.D_Image" Member="D_Images">
    <Type Name="D_Image">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_PTDIEN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Image" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Ngay_up" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Nguoi_up" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="D_PTDIEN_D_Image" Member="D_PTDIEN" ThisKey="ID_PTDIEN" OtherKey="ID_PTDIEN" Type="D_PTDIEN" IsForeignKey="true" />
    </Type>
  </Table>
</Database>