//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace CMISDongBo.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service_CCDCSoap", Namespace="http://tempuri.org/")]
    public partial class Service_CCDC : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback LDSONG_DSKHANGOperationCompleted;
        
        private System.Threading.SendOrPostCallback LDSONG_DSDDOOperationCompleted;
        
        private System.Threading.SendOrPostCallback DongBo_TreoMoiOperationCompleted;
        
        private System.Threading.SendOrPostCallback DongBo_TreoMoiKHOperationCompleted;
        
        private System.Threading.SendOrPostCallback DongBo_ThaoXuongOperationCompleted;
        
        private System.Threading.SendOrPostCallback DongBo_ThaoXuongKHOperationCompleted;
        
        private System.Threading.SendOrPostCallback DongBo_TrongKhoOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_DSCToTonkho181OperationCompleted;
        
        private System.Threading.SendOrPostCallback get_DSCToTonkho182OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service_CCDC() {
            this.Url = global::CMISDongBo.Properties.Settings.Default.CMISDongBo_WebReference_Service_CCDC;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event LDSONG_DSKHANGCompletedEventHandler LDSONG_DSKHANGCompleted;
        
        /// <remarks/>
        public event LDSONG_DSDDOCompletedEventHandler LDSONG_DSDDOCompleted;
        
        /// <remarks/>
        public event DongBo_TreoMoiCompletedEventHandler DongBo_TreoMoiCompleted;
        
        /// <remarks/>
        public event DongBo_TreoMoiKHCompletedEventHandler DongBo_TreoMoiKHCompleted;
        
        /// <remarks/>
        public event DongBo_ThaoXuongCompletedEventHandler DongBo_ThaoXuongCompleted;
        
        /// <remarks/>
        public event DongBo_ThaoXuongKHCompletedEventHandler DongBo_ThaoXuongKHCompleted;
        
        /// <remarks/>
        public event DongBo_TrongKhoCompletedEventHandler DongBo_TrongKhoCompleted;
        
        /// <remarks/>
        public event get_DSCToTonkho181CompletedEventHandler get_DSCToTonkho181Completed;
        
        /// <remarks/>
        public event get_DSCToTonkho182CompletedEventHandler get_DSCToTonkho182Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LDSONG_DSKHANG", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet LDSONG_DSKHANG(string _DVQL, System.DateTime _NGAY) {
            object[] results = this.Invoke("LDSONG_DSKHANG", new object[] {
                        _DVQL,
                        _NGAY});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void LDSONG_DSKHANGAsync(string _DVQL, System.DateTime _NGAY) {
            this.LDSONG_DSKHANGAsync(_DVQL, _NGAY, null);
        }
        
        /// <remarks/>
        public void LDSONG_DSKHANGAsync(string _DVQL, System.DateTime _NGAY, object userState) {
            if ((this.LDSONG_DSKHANGOperationCompleted == null)) {
                this.LDSONG_DSKHANGOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLDSONG_DSKHANGOperationCompleted);
            }
            this.InvokeAsync("LDSONG_DSKHANG", new object[] {
                        _DVQL,
                        _NGAY}, this.LDSONG_DSKHANGOperationCompleted, userState);
        }
        
        private void OnLDSONG_DSKHANGOperationCompleted(object arg) {
            if ((this.LDSONG_DSKHANGCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LDSONG_DSKHANGCompleted(this, new LDSONG_DSKHANGCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LDSONG_DSDDO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet LDSONG_DSDDO(string _DVQL, System.DateTime _NGAY) {
            object[] results = this.Invoke("LDSONG_DSDDO", new object[] {
                        _DVQL,
                        _NGAY});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void LDSONG_DSDDOAsync(string _DVQL, System.DateTime _NGAY) {
            this.LDSONG_DSDDOAsync(_DVQL, _NGAY, null);
        }
        
        /// <remarks/>
        public void LDSONG_DSDDOAsync(string _DVQL, System.DateTime _NGAY, object userState) {
            if ((this.LDSONG_DSDDOOperationCompleted == null)) {
                this.LDSONG_DSDDOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLDSONG_DSDDOOperationCompleted);
            }
            this.InvokeAsync("LDSONG_DSDDO", new object[] {
                        _DVQL,
                        _NGAY}, this.LDSONG_DSDDOOperationCompleted, userState);
        }
        
        private void OnLDSONG_DSDDOOperationCompleted(object arg) {
            if ((this.LDSONG_DSDDOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LDSONG_DSDDOCompleted(this, new LDSONG_DSDDOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DongBo_TreoMoi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet DongBo_TreoMoi(string _DVQL, System.DateTime _NGAY) {
            object[] results = this.Invoke("DongBo_TreoMoi", new object[] {
                        _DVQL,
                        _NGAY});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void DongBo_TreoMoiAsync(string _DVQL, System.DateTime _NGAY) {
            this.DongBo_TreoMoiAsync(_DVQL, _NGAY, null);
        }
        
        /// <remarks/>
        public void DongBo_TreoMoiAsync(string _DVQL, System.DateTime _NGAY, object userState) {
            if ((this.DongBo_TreoMoiOperationCompleted == null)) {
                this.DongBo_TreoMoiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDongBo_TreoMoiOperationCompleted);
            }
            this.InvokeAsync("DongBo_TreoMoi", new object[] {
                        _DVQL,
                        _NGAY}, this.DongBo_TreoMoiOperationCompleted, userState);
        }
        
        private void OnDongBo_TreoMoiOperationCompleted(object arg) {
            if ((this.DongBo_TreoMoiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DongBo_TreoMoiCompleted(this, new DongBo_TreoMoiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DongBo_TreoMoiKH", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet DongBo_TreoMoiKH(string _DVQL, System.DateTime _NGAY) {
            object[] results = this.Invoke("DongBo_TreoMoiKH", new object[] {
                        _DVQL,
                        _NGAY});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void DongBo_TreoMoiKHAsync(string _DVQL, System.DateTime _NGAY) {
            this.DongBo_TreoMoiKHAsync(_DVQL, _NGAY, null);
        }
        
        /// <remarks/>
        public void DongBo_TreoMoiKHAsync(string _DVQL, System.DateTime _NGAY, object userState) {
            if ((this.DongBo_TreoMoiKHOperationCompleted == null)) {
                this.DongBo_TreoMoiKHOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDongBo_TreoMoiKHOperationCompleted);
            }
            this.InvokeAsync("DongBo_TreoMoiKH", new object[] {
                        _DVQL,
                        _NGAY}, this.DongBo_TreoMoiKHOperationCompleted, userState);
        }
        
        private void OnDongBo_TreoMoiKHOperationCompleted(object arg) {
            if ((this.DongBo_TreoMoiKHCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DongBo_TreoMoiKHCompleted(this, new DongBo_TreoMoiKHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DongBo_ThaoXuong", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet DongBo_ThaoXuong(string _DVQL, System.DateTime _NGAY) {
            object[] results = this.Invoke("DongBo_ThaoXuong", new object[] {
                        _DVQL,
                        _NGAY});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void DongBo_ThaoXuongAsync(string _DVQL, System.DateTime _NGAY) {
            this.DongBo_ThaoXuongAsync(_DVQL, _NGAY, null);
        }
        
        /// <remarks/>
        public void DongBo_ThaoXuongAsync(string _DVQL, System.DateTime _NGAY, object userState) {
            if ((this.DongBo_ThaoXuongOperationCompleted == null)) {
                this.DongBo_ThaoXuongOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDongBo_ThaoXuongOperationCompleted);
            }
            this.InvokeAsync("DongBo_ThaoXuong", new object[] {
                        _DVQL,
                        _NGAY}, this.DongBo_ThaoXuongOperationCompleted, userState);
        }
        
        private void OnDongBo_ThaoXuongOperationCompleted(object arg) {
            if ((this.DongBo_ThaoXuongCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DongBo_ThaoXuongCompleted(this, new DongBo_ThaoXuongCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DongBo_ThaoXuongKH", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet DongBo_ThaoXuongKH(string _DVQL, System.DateTime _NGAY) {
            object[] results = this.Invoke("DongBo_ThaoXuongKH", new object[] {
                        _DVQL,
                        _NGAY});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void DongBo_ThaoXuongKHAsync(string _DVQL, System.DateTime _NGAY) {
            this.DongBo_ThaoXuongKHAsync(_DVQL, _NGAY, null);
        }
        
        /// <remarks/>
        public void DongBo_ThaoXuongKHAsync(string _DVQL, System.DateTime _NGAY, object userState) {
            if ((this.DongBo_ThaoXuongKHOperationCompleted == null)) {
                this.DongBo_ThaoXuongKHOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDongBo_ThaoXuongKHOperationCompleted);
            }
            this.InvokeAsync("DongBo_ThaoXuongKH", new object[] {
                        _DVQL,
                        _NGAY}, this.DongBo_ThaoXuongKHOperationCompleted, userState);
        }
        
        private void OnDongBo_ThaoXuongKHOperationCompleted(object arg) {
            if ((this.DongBo_ThaoXuongKHCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DongBo_ThaoXuongKHCompleted(this, new DongBo_ThaoXuongKHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DongBo_TrongKho", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet DongBo_TrongKho(string _DVQL, System.DateTime _NGAY) {
            object[] results = this.Invoke("DongBo_TrongKho", new object[] {
                        _DVQL,
                        _NGAY});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void DongBo_TrongKhoAsync(string _DVQL, System.DateTime _NGAY) {
            this.DongBo_TrongKhoAsync(_DVQL, _NGAY, null);
        }
        
        /// <remarks/>
        public void DongBo_TrongKhoAsync(string _DVQL, System.DateTime _NGAY, object userState) {
            if ((this.DongBo_TrongKhoOperationCompleted == null)) {
                this.DongBo_TrongKhoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDongBo_TrongKhoOperationCompleted);
            }
            this.InvokeAsync("DongBo_TrongKho", new object[] {
                        _DVQL,
                        _NGAY}, this.DongBo_TrongKhoOperationCompleted, userState);
        }
        
        private void OnDongBo_TrongKhoOperationCompleted(object arg) {
            if ((this.DongBo_TrongKhoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DongBo_TrongKhoCompleted(this, new DongBo_TrongKhoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_DSCToTonkho181", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet get_DSCToTonkho181(string _DVQL, System.DateTime _TUNGAY, System.DateTime _DENNGAY) {
            object[] results = this.Invoke("get_DSCToTonkho181", new object[] {
                        _DVQL,
                        _TUNGAY,
                        _DENNGAY});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void get_DSCToTonkho181Async(string _DVQL, System.DateTime _TUNGAY, System.DateTime _DENNGAY) {
            this.get_DSCToTonkho181Async(_DVQL, _TUNGAY, _DENNGAY, null);
        }
        
        /// <remarks/>
        public void get_DSCToTonkho181Async(string _DVQL, System.DateTime _TUNGAY, System.DateTime _DENNGAY, object userState) {
            if ((this.get_DSCToTonkho181OperationCompleted == null)) {
                this.get_DSCToTonkho181OperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_DSCToTonkho181OperationCompleted);
            }
            this.InvokeAsync("get_DSCToTonkho181", new object[] {
                        _DVQL,
                        _TUNGAY,
                        _DENNGAY}, this.get_DSCToTonkho181OperationCompleted, userState);
        }
        
        private void Onget_DSCToTonkho181OperationCompleted(object arg) {
            if ((this.get_DSCToTonkho181Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_DSCToTonkho181Completed(this, new get_DSCToTonkho181CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_DSCToTonkho182", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet get_DSCToTonkho182(string _DVQL, string _KHO, int _THANG, int _NAM) {
            object[] results = this.Invoke("get_DSCToTonkho182", new object[] {
                        _DVQL,
                        _KHO,
                        _THANG,
                        _NAM});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void get_DSCToTonkho182Async(string _DVQL, string _KHO, int _THANG, int _NAM) {
            this.get_DSCToTonkho182Async(_DVQL, _KHO, _THANG, _NAM, null);
        }
        
        /// <remarks/>
        public void get_DSCToTonkho182Async(string _DVQL, string _KHO, int _THANG, int _NAM, object userState) {
            if ((this.get_DSCToTonkho182OperationCompleted == null)) {
                this.get_DSCToTonkho182OperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_DSCToTonkho182OperationCompleted);
            }
            this.InvokeAsync("get_DSCToTonkho182", new object[] {
                        _DVQL,
                        _KHO,
                        _THANG,
                        _NAM}, this.get_DSCToTonkho182OperationCompleted, userState);
        }
        
        private void Onget_DSCToTonkho182OperationCompleted(object arg) {
            if ((this.get_DSCToTonkho182Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_DSCToTonkho182Completed(this, new get_DSCToTonkho182CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void LDSONG_DSKHANGCompletedEventHandler(object sender, LDSONG_DSKHANGCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LDSONG_DSKHANGCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LDSONG_DSKHANGCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void LDSONG_DSDDOCompletedEventHandler(object sender, LDSONG_DSDDOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LDSONG_DSDDOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LDSONG_DSDDOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void DongBo_TreoMoiCompletedEventHandler(object sender, DongBo_TreoMoiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DongBo_TreoMoiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DongBo_TreoMoiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void DongBo_TreoMoiKHCompletedEventHandler(object sender, DongBo_TreoMoiKHCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DongBo_TreoMoiKHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DongBo_TreoMoiKHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void DongBo_ThaoXuongCompletedEventHandler(object sender, DongBo_ThaoXuongCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DongBo_ThaoXuongCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DongBo_ThaoXuongCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void DongBo_ThaoXuongKHCompletedEventHandler(object sender, DongBo_ThaoXuongKHCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DongBo_ThaoXuongKHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DongBo_ThaoXuongKHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void DongBo_TrongKhoCompletedEventHandler(object sender, DongBo_TrongKhoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DongBo_TrongKhoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DongBo_TrongKhoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void get_DSCToTonkho181CompletedEventHandler(object sender, get_DSCToTonkho181CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_DSCToTonkho181CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_DSCToTonkho181CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void get_DSCToTonkho182CompletedEventHandler(object sender, get_DSCToTonkho182CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_DSCToTonkho182CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_DSCToTonkho182CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591