#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMISDongBo
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LDSong")]
	public partial class CMISDBODataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertK_DIEM_DO_TMP(K_DIEM_DO_TMP instance);
    partial void UpdateK_DIEM_DO_TMP(K_DIEM_DO_TMP instance);
    partial void DeleteK_DIEM_DO_TMP(K_DIEM_DO_TMP instance);
    partial void InsertK_KHACH_HANG_TMP(K_KHACH_HANG_TMP instance);
    partial void UpdateK_KHACH_HANG_TMP(K_KHACH_HANG_TMP instance);
    partial void DeleteK_KHACH_HANG_TMP(K_KHACH_HANG_TMP instance);
    partial void InsertK_DONGBO_CMI(K_DONGBO_CMI instance);
    partial void UpdateK_DONGBO_CMI(K_DONGBO_CMI instance);
    partial void DeleteK_DONGBO_CMI(K_DONGBO_CMI instance);
    #endregion
		
		public CMISDBODataContext() : 
				base(global::CMISDongBo.Properties.Settings.Default.LDSongConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CMISDBODataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CMISDBODataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CMISDBODataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CMISDBODataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<K_DIEM_DO_TMP> K_DIEM_DO_TMPs
		{
			get
			{
				return this.GetTable<K_DIEM_DO_TMP>();
			}
		}
		
		public System.Data.Linq.Table<K_KHACH_HANG_TMP> K_KHACH_HANG_TMPs
		{
			get
			{
				return this.GetTable<K_KHACH_HANG_TMP>();
			}
		}
		
		public System.Data.Linq.Table<K_DONGBO_CMI> K_DONGBO_CMIs
		{
			get
			{
				return this.GetTable<K_DONGBO_CMI>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_CHUYENDL_KHANG")]
		public int sp_CHUYENDL_KHANG([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaDV", DbType="NVarChar(6)")] string maDV)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maDV);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_CHUYENDL_DDO")]
		public int sp_CHUYENDL_DDO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaDV", DbType="NVarChar(6)")] string maDV)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maDV);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.K_DIEM_DO_TMP")]
	public partial class K_DIEM_DO_TMP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MA_DVIQLY;
		
		private string _MA_KHANG;
		
		private string _MA_DDO;
		
		private string _SO_CTO;
		
		private string _MA_SOGCS;
		
		private string _STT;
		
		private string _MA_TRAM;
		
		private string _MA_LO;
		
		private string _SO_COT;
		
		private string _SO_HOM;
		
		private System.Nullable<System.DateTime> _NGAY_DBO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_DVIQLYChanging(string value);
    partial void OnMA_DVIQLYChanged();
    partial void OnMA_KHANGChanging(string value);
    partial void OnMA_KHANGChanged();
    partial void OnMA_DDOChanging(string value);
    partial void OnMA_DDOChanged();
    partial void OnSO_CTOChanging(string value);
    partial void OnSO_CTOChanged();
    partial void OnMA_SOGCSChanging(string value);
    partial void OnMA_SOGCSChanged();
    partial void OnSTTChanging(string value);
    partial void OnSTTChanged();
    partial void OnMA_TRAMChanging(string value);
    partial void OnMA_TRAMChanged();
    partial void OnMA_LOChanging(string value);
    partial void OnMA_LOChanged();
    partial void OnSO_COTChanging(string value);
    partial void OnSO_COTChanged();
    partial void OnSO_HOMChanging(string value);
    partial void OnSO_HOMChanged();
    partial void OnNGAY_DBOChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAY_DBOChanged();
    #endregion
		
		public K_DIEM_DO_TMP()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_DVIQLY", DbType="NVarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MA_DVIQLY
		{
			get
			{
				return this._MA_DVIQLY;
			}
			set
			{
				if ((this._MA_DVIQLY != value))
				{
					this.OnMA_DVIQLYChanging(value);
					this.SendPropertyChanging();
					this._MA_DVIQLY = value;
					this.SendPropertyChanged("MA_DVIQLY");
					this.OnMA_DVIQLYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_KHANG", DbType="NVarChar(13)")]
		public string MA_KHANG
		{
			get
			{
				return this._MA_KHANG;
			}
			set
			{
				if ((this._MA_KHANG != value))
				{
					this.OnMA_KHANGChanging(value);
					this.SendPropertyChanging();
					this._MA_KHANG = value;
					this.SendPropertyChanged("MA_KHANG");
					this.OnMA_KHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_DDO", DbType="NVarChar(16) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MA_DDO
		{
			get
			{
				return this._MA_DDO;
			}
			set
			{
				if ((this._MA_DDO != value))
				{
					this.OnMA_DDOChanging(value);
					this.SendPropertyChanging();
					this._MA_DDO = value;
					this.SendPropertyChanged("MA_DDO");
					this.OnMA_DDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SO_CTO", DbType="NVarChar(12)")]
		public string SO_CTO
		{
			get
			{
				return this._SO_CTO;
			}
			set
			{
				if ((this._SO_CTO != value))
				{
					this.OnSO_CTOChanging(value);
					this.SendPropertyChanging();
					this._SO_CTO = value;
					this.SendPropertyChanged("SO_CTO");
					this.OnSO_CTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_SOGCS", DbType="NVarChar(9)")]
		public string MA_SOGCS
		{
			get
			{
				return this._MA_SOGCS;
			}
			set
			{
				if ((this._MA_SOGCS != value))
				{
					this.OnMA_SOGCSChanging(value);
					this.SendPropertyChanging();
					this._MA_SOGCS = value;
					this.SendPropertyChanged("MA_SOGCS");
					this.OnMA_SOGCSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", DbType="NVarChar(6)")]
		public string STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this.OnSTTChanging(value);
					this.SendPropertyChanging();
					this._STT = value;
					this.SendPropertyChanged("STT");
					this.OnSTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_TRAM", DbType="NVarChar(9)")]
		public string MA_TRAM
		{
			get
			{
				return this._MA_TRAM;
			}
			set
			{
				if ((this._MA_TRAM != value))
				{
					this.OnMA_TRAMChanging(value);
					this.SendPropertyChanging();
					this._MA_TRAM = value;
					this.SendPropertyChanged("MA_TRAM");
					this.OnMA_TRAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_LO", DbType="NVarChar(9)")]
		public string MA_LO
		{
			get
			{
				return this._MA_LO;
			}
			set
			{
				if ((this._MA_LO != value))
				{
					this.OnMA_LOChanging(value);
					this.SendPropertyChanging();
					this._MA_LO = value;
					this.SendPropertyChanged("MA_LO");
					this.OnMA_LOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SO_COT", DbType="NVarChar(40)")]
		public string SO_COT
		{
			get
			{
				return this._SO_COT;
			}
			set
			{
				if ((this._SO_COT != value))
				{
					this.OnSO_COTChanging(value);
					this.SendPropertyChanging();
					this._SO_COT = value;
					this.SendPropertyChanged("SO_COT");
					this.OnSO_COTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SO_HOM", DbType="NVarChar(20)")]
		public string SO_HOM
		{
			get
			{
				return this._SO_HOM;
			}
			set
			{
				if ((this._SO_HOM != value))
				{
					this.OnSO_HOMChanging(value);
					this.SendPropertyChanging();
					this._SO_HOM = value;
					this.SendPropertyChanged("SO_HOM");
					this.OnSO_HOMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAY_DBO", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAY_DBO
		{
			get
			{
				return this._NGAY_DBO;
			}
			set
			{
				if ((this._NGAY_DBO != value))
				{
					this.OnNGAY_DBOChanging(value);
					this.SendPropertyChanging();
					this._NGAY_DBO = value;
					this.SendPropertyChanged("NGAY_DBO");
					this.OnNGAY_DBOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.K_KHACH_HANG_TMP")]
	public partial class K_KHACH_HANG_TMP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MA_DVIQLY;
		
		private string _MA_KHANG;
		
		private string _TEN_KHANG;
		
		private string _DIA_CHI;
		
		private string _DIEN_THOAI;
		
		private System.Nullable<System.DateTime> _NGAY_DBO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_DVIQLYChanging(string value);
    partial void OnMA_DVIQLYChanged();
    partial void OnMA_KHANGChanging(string value);
    partial void OnMA_KHANGChanged();
    partial void OnTEN_KHANGChanging(string value);
    partial void OnTEN_KHANGChanged();
    partial void OnDIA_CHIChanging(string value);
    partial void OnDIA_CHIChanged();
    partial void OnDIEN_THOAIChanging(string value);
    partial void OnDIEN_THOAIChanged();
    partial void OnNGAY_DBOChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAY_DBOChanged();
    #endregion
		
		public K_KHACH_HANG_TMP()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_DVIQLY", DbType="NVarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MA_DVIQLY
		{
			get
			{
				return this._MA_DVIQLY;
			}
			set
			{
				if ((this._MA_DVIQLY != value))
				{
					this.OnMA_DVIQLYChanging(value);
					this.SendPropertyChanging();
					this._MA_DVIQLY = value;
					this.SendPropertyChanged("MA_DVIQLY");
					this.OnMA_DVIQLYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_KHANG", DbType="NVarChar(13) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MA_KHANG
		{
			get
			{
				return this._MA_KHANG;
			}
			set
			{
				if ((this._MA_KHANG != value))
				{
					this.OnMA_KHANGChanging(value);
					this.SendPropertyChanging();
					this._MA_KHANG = value;
					this.SendPropertyChanged("MA_KHANG");
					this.OnMA_KHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_KHANG", DbType="NVarChar(150)")]
		public string TEN_KHANG
		{
			get
			{
				return this._TEN_KHANG;
			}
			set
			{
				if ((this._TEN_KHANG != value))
				{
					this.OnTEN_KHANGChanging(value);
					this.SendPropertyChanging();
					this._TEN_KHANG = value;
					this.SendPropertyChanged("TEN_KHANG");
					this.OnTEN_KHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIA_CHI", DbType="NVarChar(150)")]
		public string DIA_CHI
		{
			get
			{
				return this._DIA_CHI;
			}
			set
			{
				if ((this._DIA_CHI != value))
				{
					this.OnDIA_CHIChanging(value);
					this.SendPropertyChanging();
					this._DIA_CHI = value;
					this.SendPropertyChanged("DIA_CHI");
					this.OnDIA_CHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIEN_THOAI", DbType="NVarChar(11)")]
		public string DIEN_THOAI
		{
			get
			{
				return this._DIEN_THOAI;
			}
			set
			{
				if ((this._DIEN_THOAI != value))
				{
					this.OnDIEN_THOAIChanging(value);
					this.SendPropertyChanging();
					this._DIEN_THOAI = value;
					this.SendPropertyChanged("DIEN_THOAI");
					this.OnDIEN_THOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAY_DBO", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAY_DBO
		{
			get
			{
				return this._NGAY_DBO;
			}
			set
			{
				if ((this._NGAY_DBO != value))
				{
					this.OnNGAY_DBOChanging(value);
					this.SendPropertyChanging();
					this._NGAY_DBO = value;
					this.SendPropertyChanged("NGAY_DBO");
					this.OnNGAY_DBOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.K_DONGBO_CMIS")]
	public partial class K_DONGBO_CMI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MA_DVIQLY;
		
		private System.Nullable<System.DateTime> _NGAY_KH;
		
		private System.Nullable<System.DateTime> _NGAY_DD;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_DVIQLYChanging(string value);
    partial void OnMA_DVIQLYChanged();
    partial void OnNGAY_KHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAY_KHChanged();
    partial void OnNGAY_DDChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAY_DDChanged();
    #endregion
		
		public K_DONGBO_CMI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_DVIQLY", DbType="NVarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MA_DVIQLY
		{
			get
			{
				return this._MA_DVIQLY;
			}
			set
			{
				if ((this._MA_DVIQLY != value))
				{
					this.OnMA_DVIQLYChanging(value);
					this.SendPropertyChanging();
					this._MA_DVIQLY = value;
					this.SendPropertyChanged("MA_DVIQLY");
					this.OnMA_DVIQLYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAY_KH", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAY_KH
		{
			get
			{
				return this._NGAY_KH;
			}
			set
			{
				if ((this._NGAY_KH != value))
				{
					this.OnNGAY_KHChanging(value);
					this.SendPropertyChanging();
					this._NGAY_KH = value;
					this.SendPropertyChanged("NGAY_KH");
					this.OnNGAY_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAY_DD", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAY_DD
		{
			get
			{
				return this._NGAY_DD;
			}
			set
			{
				if ((this._NGAY_DD != value))
				{
					this.OnNGAY_DDChanging(value);
					this.SendPropertyChanging();
					this._NGAY_DD = value;
					this.SendPropertyChanged("NGAY_DD");
					this.OnNGAY_DDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
