truncate table D_PTDIEN
truncate table D_QHE_PTDIEN
truncate table M_VITRI

DBCC CHECKIDENT ('[D_PTDIEN]', RESEED, 0)
DBCC CHECKIDENT ('[D_QHE_PTDIEN]', RESEED, 0)

-- LAY DUONG DAY
INSERT INTO D_PTDIEN(MA_DVQLY,MA_PMIS,MA_PMISCHA,ten_CAPDA,MA_CAPDA,LOAI_PTDIEN)
select orgid,[ASSETID],assetid_parent,ULEVELID,'01','DZ'
from openquery([NBPCSRV16],
'select tt.orgid,tt.[ASSETID],tt.assetid_parent,tt.ULEVELID from [PMIS].[dbo].ZAG_LOCATION_DZ dz INNER JOIN [PMIS].[dbo].A_ASSET tt ON dz.OBJID = tt.ASSETID')
 --where assetid_parent = 'PN.214288' OR [ASSETID] = 'PN.214288'
 
 -- LAY TOA DO VI TRI
 INSERT INTO M_VITRI(MA_DVQLY,ID_PTDIEN,MA_PMIS,TOA_DO)
 select orgid,ROW_NUMBER() OVER(ORDER BY ASSETID),[ASSETID],TOA_DO=geometry::STGeomFromText(POS,0)
from openquery([NBPCSRV16],
'select tt.orgid,tt.[ASSETID],tt.assetid_parent,POS=dz.TOA_DO.STAsText() from [PMIS].[dbo].ZAG_LOCATION_DZ dz INNER JOIN [PMIS].[dbo].A_ASSET tt ON dz.OBJID = tt.ASSETID')
 --where assetid_parent = 'PN.214288' OR [ASSETID] = 'PN.214288'

 /*
 -- TAO QUAN HE
 INSERT INTO D_QHE_PTDIEN(ID_PTDIEN,ID_PTCHA,NGAY_HLUC)
SELECT C.ID_PTDIEN,ISNULL( P.ID_PTDIEN,0),GETDATE()
FROM D_PTDIEN C JOIN D_PTDIEN P ON C.MA_PMISCHA = P.MA_PMIS
 
 -- CAP NHAT VI TRI THEO ID
 UPDATE M_VITRI SET ID_PTDIEN = PT.ID_PTDIEN FROM M_VITRI VT JOIN D_PTDIEN PT ON VT.MA_DVQLY = PT.MA_DVQLY AND VT.MA_PMIS = PT.MA_PMIS
*/

select count(*) from M_VITRI
-- LAY VI TRI
INSERT INTO D_PTDIEN(MA_DVQLY,MA_PMIS,MA_PMISCHA,ten_CAPDA,MA_CAPDA,LOAI_PTDIEN,TEN_PTDIEN)
select orgid,[ASSETID],assetid_parent,ULEVELID,'01','VT',ASSETDESC
from openquery([NBPCSRV16],
'select vt.ORGID, vt.ASSETID,vt.ASSETID_PARENT,vt.ULEVELID,vt.ASSETDESC from [PMIS].[dbo].ZAG_LOCATION_VT_DB vt INNER JOIN [PMIS].[dbo].ZAG_LOCATION td ON vt.ASSETID = td.OBJID INNER JOIN A_ASSET tt ON vt.ASSETID = tt.ASSETID')
 --where assetid_parent = 'PN.214288' OR [ASSETID] = 'PN.214288'

 -- TAO QUAN HE
 INSERT INTO D_QHE_PTDIEN(ID_PTDIEN,ID_PTCHA,NGAY_HLUC)
SELECT C.ID_PTDIEN,ISNULL( P.ID_PTDIEN,0),GETDATE()
FROM D_PTDIEN C JOIN D_PTDIEN P ON C.MA_PMISCHA = P.MA_PMIS

-- LAY TOA DO VI TRI
 INSERT INTO M_VITRI(MA_DVQLY,ID_PTDIEN,MA_PMIS,TOA_DO)
 select orgid,ROW_NUMBER() OVER(ORDER BY ASSETID)+2351,[ASSETID],TOA_DO=geometry::STGeomFromText(POS,0)
from openquery([NBPCSRV16],
'select vt.orgid,vt.[ASSETID],vt.assetid_parent,POS=td.TOA_DO.STAsText() from [PMIS].[dbo].ZAG_LOCATION_VT_DB vt INNER JOIN [PMIS].[dbo].ZAG_LOCATION td ON vt.ASSETID = td.OBJID INNER JOIN A_ASSET tt ON vt.ASSETID = tt.ASSETID')
 --where assetid_parent = 'PN.214288' OR [ASSETID] = 'PN.214288'
 
 -- CAP NHAT VI TRI THEO ID
 UPDATE M_VITRI SET ID_PTDIEN = ID_PTDIEN + (SELECT COUNT(*) FROM D_PTDIEN)
 UPDATE M_VITRI SET MA_PTDIEN = 'TRUNG' WHERE MA_PMIS IN (
	SELECT MA_PMIS FROM M_VITRI GROUP BY MA_DVQLY,MA_PMIS HAVING COUNT(*) > 1
 )
  
 UPDATE M_VITRI SET ID_PTDIEN = PT.ID_PTDIEN FROM M_VITRI VT JOIN D_PTDIEN PT ON VT.MA_DVQLY = PT.MA_DVQLY AND VT.MA_PMIS = PT.MA_PMIS WHERE MA_PTDIEN IS NULL

 SELECT DISTINCT TEN_CAPDA FROM D_PTDIEN

 UPDATE D_PTDIEN SET MA_CAPDA = '03' WHERE TEN_CAPDA = 'U10'
 UPDATE D_PTDIEN SET MA_CAPDA = '05' WHERE TEN_CAPDA = 'U22'
 UPDATE D_PTDIEN SET MA_CAPDA = '06' WHERE TEN_CAPDA = 'U35'
 UPDATE D_PTDIEN SET MA_CAPDA = '08' WHERE TEN_CAPDA = 'U110'

